#!/bin/bash


# Description: script to do inventory on a server and decide its fate.
# Author: Liliane
# Date: Jan 13


# Check OS version
OS=`cat /etc/*release |grep PRETTY_NAME | awk -F= '{print$2}'`
echo -e "\nOS version : $OS.\n"
sleep 2
# Check size of memory
Mem=`cat /proc/meminfo |grep MemTotal | awk -F: '{print$2}'`
echo -e "\nMemory (KB) : $Mem\n"
sleep 2
# Check size of harddrive
Disk=`lsblk | grep disk | awk '{print$4}'`
echo -e "\nHardrive (G) :  $Disk\n"
sleep 2
# Check the CPU core
echo
echo -n "CPU cores:"
 cat /proc/cpuinfo |grep "cpu cores" |awk -F: '{print$2}'
sleep 2
# Check the processor speed
echo
echo -n "Processor speed (MHz):"
  lscpu |grep "CPU MHz" |awk -F: '{print$2}'
sleep 2
#check kernel version
Ker=`iostat |grep Linux |awk '{print$2}' |awk -F. '{print$1}'`
KER=`iostat |grep Linux |awk '{print$2}'`
if [ $Ker -ge 5 ]
then
echo -e "\nThis system is update and its kernel version is $KER\n"
else
echo -e "\nThis system is not  update and its kernel version is $KER\n"
fi
sleep 2
#check the computer architecture
Arch=`arch |awk -F_ '{print$2}'`
if [ $Arch -ne 32 ]
then
echo -e "\nComputer architecture : $Arch bits\n"
fi
sleep 2
# Check the hostname
echo -e "\nHostname : `hostnamectl |grep hostname |awk -F: '{print$2}'`\n"
sleep 2
# check the ip address
IP=`ifconfig |grep "255.255.255.0" |awk '{print$2}'`
echo -e "\nIP address : $IP\n"
sleep 2
# Check all opened ports
echo -e "\nAll opened ports :\n"
netstat -plunt | grep LISTEN
sleep 2
echo
echo
#Check if apache2 is installed
apache2 -v
if [  $? -eq 0 ]
then
echo -e "\nApache2 is installed\n"
fi
sleep 2
#Check if docker is installed
docker -v
if [  $? -eq 0 ]
then
echo -e "\nDocker is installed\n"
fi
sleep 2
# Check if the webserver is up and running
echo
netstat -plunt | grep apache2
if [  $? -eq 0 ]
then
echo -e "\nThe webserver is up and running\n"
fi
sleep 2
# Check DNS (Domain Name System)
echo -e "\nDNS : \n"
nmcli dev show | grep IP4.DNS
echo
echo
sleep 2
# Check the Manufacturer
dmidecode -t system | grep Manufacturer
echo
echo
sleep 2
# Check the model of the machine
dmidecode -t system | grep Product
sleep 2
echo
# Check the MAC address (Media Access Control address)
echo -e "\nMAC address : `ifconfig |grep 1000 |grep ether |awk '{print$2}'`\n"
sleep 2
# a summary of inventory
echo -e "\nA summary of inventory\n"
inxi



CHECK CHARACTERISTIC OF A Linux SERVER THAT NEED TO BE DECOMMISSIONED
To do that , we run some commands:   
    
$ lsblk  	-> to display the size of the hard drive with all the partitions		

$ lscpu 
$ nproc 
$ cat /proc/cpuinfo	  -> to display the characteristic of the cpu	

$ free -m  
$ top  
$ free -g 
$ cat /proc/meminfo	  -> to check the memory		

$ cat /etc/*release	  -> to check the OS version of your Linux server	

$ uname -r  
$ uname -a  
$ iostat  
$ cat /proc/version	   ->  to check the Kernel version

$ uname -m 
$ arch  
$ getconf LONG_BIT	  ->  to print the computer architecture	

$ sudo lsof -i -P -n | grep LISTEN
$ sudo netstat -tulpn | grep LISTEN -> to check if port is in use
